cli: cli.o threaded_bst.o
	gcc -g -pedantic -Wall cli.o threaded_bst.o -o cli

cli.o: cli.c
	gcc -c -pedantic -Wall cli.c -o cli.o

threaded_bst.o: threaded_bst.c
	gcc -c -pedantic -Wall threaded_bst.c -o threaded_bst.o